name: project-name
version: 0.1.0.0
synopsis: project-description
description: Please see the README at <https://github.com/jwoudenberg/project-name>.
author: Jasper Woudenberg
maintainer: mail@jasperwoudenberg.com
copyright: project-year Jasper Woudenberg
homepage: https://github.com/jwoudenberg/project-name#readme
license-file: LICENSE
github: jwoudenberg/project-name
extra-doc-files:
- README.md
library:
  exposed-modules:
  - ProjectName
  source-dirs: src
executables:
  project-name:
    dependencies:
    - project-name
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts "-with-rtsopts=-N -T"
    - -O2
dependencies:
- base >= 4.10.1.0 && < 5
ghc-options:
- -Wall
- -Werror
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wpartial-fields
- -Wredundant-constraints
- -Wincomplete-uni-patterns
default-extensions:
- DeriveGeneric
- GeneralizedNewtypeDeriving
- NamedFieldPuns
- NumericUnderscores
- OverloadedStrings
- ScopedTypeVariables
- StrictData
